name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
  
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
         go-version-file: go.mod
         cache: true

    # - name: Run Tests
    #   run: go test -v ./...

    - name: Build API
      run: go build -o api ./cmd/api

    - name: Build Docker image
      run: docker build -t go-server .